// Code generated by copier. DO NOT EDIT.

package local

import "github.com/shagohead/copier/internal/customtypes"

func (d *Receiver) CopyFromArgument(s *Argument) {
	d.SomeField = s.SomeField
	d.IntField = s.IntField
}

func (s *Receiver) CopyIntoDestination(d *Destination) {
	d.SomeField = s.SomeField
	d.IntField = s.IntField
}

func (d *StructFields) CopyFrom(s *customtypes.StructFields) {
	if s.EventID.Set {
		d.EventID.Valid = true
		d.EventID.Int32 = s.EventID.Value
	}
	if s.ValueID.Set {
		d.ValueID.Valid = true
		d.ValueID.Int32 = s.ValueID.Value
	}
}

func (d *ExtendedReceiver) CopyFromExtendedArgument(s *ExtendedArgument) {
	if s.BaseFromWrapper.Set {
		d.BaseFromWrapper = s.BaseFromWrapper.Value
	}
	d.Target = s.Source
	d.IntToInt64 = int64(s.IntToInt64)
	d.BaseToAlias = CustomString(s.BaseToAlias)
	d.MapToAlias = s.MapToAlias
	if s.Wrapper2Wrapper.Set {
		d.Wrapper2Wrapper.Valid = !s.Wrapper2Wrapper.Null
		d.Wrapper2Wrapper.Int32 = s.Wrapper2Wrapper.Value
	}
	if s.FromWrappedGetter.Set {
		d.FromWrappedGetter = s.FromWrappedGetter.Value.String()
	}
	d.Int64FromTime = s.Int64FromTime.Unix()
	d.StringFromTime = s.StringFromTime.Format("2006-01-02T15:04:05 -07:00:00")
}
